### PR TITLE
vignettes: Build with gold standard content.

### PR DESCRIPTION
**Pull request by ramanshah**

### CODE REVIEW

**Comment by ramanshah** [comment]
@stephens999 When changing vignettes, I recommend keeping the html versions in sync to avoid confusion.

**Comment by stephens999** [comment]
sure - i did rerun and commit the new html i thought... but it seems i must have made a mistake
or not pushed it...

**Comment by ramanshah** [comment]
One thing is that R wants to put the `html` files in `inst/doc` and I always have to move them manually to keep them in line with the existing repo. I'm insufficiently experienced with package development to know what's recommended practice around this, so I've just been maintaining the status quo.

**Comment by stephens999** [comment]
ahh. mauybe that is why. I also don' t know what recommended practice is...

**Pull request merged**
